const mongoose = require('mongoose');

/*
 * Log Model
 * Represents a log entry generated by one of the system services.
 * Used for centralized logging and monitoring.
 */
const logSchema = new mongoose.Schema({
    service: String,
    method: String,        // GET / POST
    endpoint: String,      // /api/add , /api/report 
    status: Number,        // 200 / 400 / 500
    timestamp: Date,
    message: String
});

module.exports = mongoose.model('Log', logSchema);
